# Generated by Kavia Code Generation Agent

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicedata', '0002_invoicelist_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated.')),
                ('name', models.CharField(help_text='Human friendly name for the rule.', max_length=200)),
                ('code', models.SlugField(help_text='Unique code identifier for this rule.', max_length=64, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the rule.')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, rule will not be executed.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this run or its scope.')),
                ('scope_filters', models.JSONField(blank=True, default=dict, help_text='JSON description of the filter/scope for the run.')),
                ('invoices_count', models.PositiveIntegerField(default=0, help_text='Number of invoices included in the run.')),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('total_findings', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated.')),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('SKIP', 'Skipped'), ('ERROR', 'Error')], default='PASS', max_length=8)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Optional score or confidence.', max_digits=5, null=True)),
                ('message', models.TextField(blank=True, help_text='Additional information about this check result.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional data produced by the check.')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_checks', to='invoicedata.Invoicelist')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='audit.AuditRule')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='audit.AuditRun')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('run', 'rule', 'invoice')},
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated.')),
                ('title', models.CharField(help_text='Short summary of the finding.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the problem.')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SUPPRESSED', 'Suppressed'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=12)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON payload with context for the finding.')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audit_findings', to=settings.AUTH_USER_MODEL)),
                ('check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.AuditCheck')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='invoicedata.Invoicelist')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='audit.AuditRule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated.')),
                ('action_type', models.CharField(choices=[('COMMENT', 'Comment'), ('STATUS_CHANGE', 'Status Change'), ('ASSIGN', 'Assign'), ('SUPPRESS', 'Suppress'), ('OTHER', 'Other')], default='COMMENT', max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='audit.AuditFinding')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditrule',
            index=models.Index(fields=['code'], name='audit_auditr_code_7c7c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditrule',
            index=models.Index(fields=['is_active', 'severity'], name='audit_auditr_is_acti_36f4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditcheck',
            index=models.Index(fields=['status'], name='audit_auditc_status_4b6b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditcheck',
            index=models.Index(fields=['rule', 'invoice'], name='audit_auditc_rule_id_5ee55f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['status'], name='audit_auditf_status_6d8df7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['severity'], name='audit_auditf_severity_2a9f1a_idx'),
        ),
    ]
